[package]
authors = ["natemara <natemara@gmail.com>"]
name = "schwift"
version = "0.1.0"

[dependencies]
bincode = "0.5.6"
clap = "2.5.1"
clippy = "0.0.70"
git_hooks = "0.1.3"
peg = "0.3.11"
rand = "0.3"
rustc-serialize = "0.3.19"
stainless = "0.1.5"
