[package]
authors = ["natemara <natemara@gmail.com>"]
name = "schwift"
version = "0.1.0"

[dependencies]
clap = "2.5.2"
clippy = "0.0.79"
peg = "0.3.14"
rand = "0.3"
rustc-serialize = "0.3.19"
stainless = "0.1.6"
libloading = "0.3.0"
